export const itineraryData = [
  {
    id: "001",
    country: "Indonésie",
    island: "Bali",
    location: "Canggu",
    dateFrom: "20.11.2022",
    dateTo: "27.11.2022",
    withBreakfast: false,
    priceCZK: "2057",
    priceCZKPerNight: "294",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "1400000",
    priceSecondCurencyPerNight: "200000",
    name: "Twins Homestay",
    url: "https://goo.gl/maps/yK6UUzR59HLGgQ7F8",
    slug: "canggu",
    isTransfer: false,
  },
  {
    id: "002",
    country: "Indonésie",
    island: "Bali",
    location: "Legian - Kuta",
    dateFrom: "27.11.2022",
    dateTo: "4.12.2022",
    withBreakfast: true,
    priceCZK: "2490",
    priceCZKPerNight: "355",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "1700000",
    priceSecondCurencyPerNight: "243000",
    name: "Grand Sinar Indah",
    url: "https://goo.gl/maps/uoorAjyaMj8nhbTk7",
    slug: "legian-kuta",
    isTransfer: false,
  },
  {
    id: "003",
    country: "Indonésie",
    island: "Bali",
    location: "Uluwatu",
    dateFrom: "4.12.2022",
    dateTo: "8.12.2022",
    withBreakfast: true,
    priceCZK: "2990",
    priceCZKPerNight: "747",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "2070000",
    priceSecondCurencyPerNight: "517000",
    name: "Pondok Kembar Homesta",
    url: "https://goo.gl/maps/SpfkVsR7fpbET6vi6",
    slug: "uluwatu",
    isTransfer: false,
  },
  {
    id: "004",
    country: "Indonésie",
    island: "Nusa Penida",
    location: "",
    dateFrom: "8.12.2022",
    dateTo: "10.12.2022",
    withBreakfast: true,
    priceCZK: "612",
    priceCZKPerNight: "306",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "422000",
    priceSecondCurencyPerNight: "211000",
    name: "Green Palace Homestay",
    url: "https://goo.gl/maps/K7QuWQm2dc4nNVRbA",
    slug: "nusa-penida",
    isTransfer: false,
  },
  {
    id: "005",
    country: "Indonésie",
    island: "Nusa Penida",
    location: "",
    dateFrom: "10.12.2022",
    dateTo: "17.12.2022",
    withBreakfast: true,
    priceCZK: "2632",
    priceCZKPerNight: "376",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "1820000",
    priceSecondCurencyPerNight: "260000",
    name: "RR Cottage",
    url: "https://goo.gl/maps/heviEgf9PYvotRW8A",
    slug: "nusa-penida",
    isTransfer: false,
  },
  {
    id: "006",
    country: "Indonésie",
    island: "Gili",
    location: "",
    dateFrom: "17.12.2022",
    dateTo: "21.12.2022",
    withBreakfast: true,
    priceCZK: "1736",
    priceCZKPerNight: "434",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "1200000",
    priceSecondCurencyPerNight: "300000",
    name: "OYO 706 My Home One",
    url: "https://goo.gl/maps/J19nXqfERtNMxAnQA",
    slug: "gili",
    isTransfer: false,
  },
  {
    id: "007",
    country: "Indonésie",
    island: "Lombok",
    location: "Senggigi",
    dateFrom: "21.12.2022",
    dateTo: "28.12.2022",
    withBreakfast: true,
    priceCZK: "6186",
    priceCZKPerNight: "883",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "4270000",
    priceSecondCurencyPerNight: "610000",
    name: "Cafe Alberto B and B",
    url: "https://goo.gl/maps/B7bk2sU4gXSTH3sKA",
    slug: "senggigi",
    isTransfer: false,
  },
  {
    id: "008",
    country: "Indonésie",
    island: "Lombok",
    location: "Kuta",
    dateFrom: "28.12.2023",
    dateTo: "12.1.2023",
    withBreakfast: false,
    priceCZK: "6995",
    priceCZKPerNight: "466",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "4840000",
    priceSecondCurencyPerNight: "322000",
    name: "Lavella Villas",
    url: "https://goo.gl/maps/RCCVymmor7e8HV5S8",
    slug: "kuta",
    isTransfer: false,
  },
  {
    id: "009",
    country: "Indonésie",
    island: "Bali",
    location: "Legian - Kuta",
    dateFrom: "12.1.2023",
    dateTo: "18.1.2023",
    withBreakfast: false,
    priceCZK: "1713",
    priceCZKPerNight: "286",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "1200000",
    priceSecondCurencyPerNight: "200000",
    name: "Grand Sinar Indah",
    url: "https://goo.gl/maps/uoorAjyaMj8nhbTk7",
    slug: "legian-kuta-2",
    isTransfer: false,
  },
  {
    id: "010",
    country: "Indonésie",
    island: "Bali",
    location: "",
    dateFrom: "18.1.2023",
    dateTo: "19.1.2023",
    withBreakfast: false,
    priceCZK: "",
    priceCZKPerNight: "",
    typeOfSecondCurency: "PHP",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "přelet Bali - Palawan",
    url: "",
    slug: "",
    isTransfer: true,
  },
  {
    id: "011",
    country: "Filipíny",
    island: "Palawan",
    location: "Port Barton",
    dateFrom: "19.1.2023",
    dateTo: "21.1.2023",
    withBreakfast: true,
    priceCZK: "1930",
    priceCZKPerNight: "965",
    typeOfSecondCurency: "PHP",
    priceSecondCurency: "4760",
    priceSecondCurencyPerNight: "2380",
    name: "Hotel Oasis Port Barton",
    url: "https://goo.gl/maps/MRpjtUjRyT5VbfKR7",
    slug: "port-barton",
    isTransfer: false,
  },
  {
    id: "012",
    country: "Filipíny",
    island: "Palawan",
    location: "El Nido",
    dateFrom: "21.1.2023",
    dateTo: "22.1.2023",
    withBreakfast: false,
    priceCZK: "770",
    priceCZKPerNight: "770",
    typeOfSecondCurency: "PHP",
    priceSecondCurency: "1900",
    priceSecondCurencyPerNight: "1900",
    name: "Anang Balay Turista",
    url: "https://goo.gl/maps/SaoF5bWAnSnR3xUW6",
    slug: "el-nido",
    isTransfer: false,
  },
  {
    id: "013",
    country: "Filipíny",
    island: "Palawan",
    location: "El Nido",
    dateFrom: "22.1.2023",
    dateTo: "26.1.2023",
    withBreakfast: false,
    priceCZK: "3385",
    priceCZKPerNight: "846",
    typeOfSecondCurency: "PHP",
    priceSecondCurency: "8350",
    priceSecondCurencyPerNight: "2080",
    name: "Ashoka",
    url: "https://goo.gl/maps/wMkQyARu8RtgAQCu9",
    slug: "el-nido",
    isTransfer: false,
  },
  {
    id: "014",
    country: "Filipíny",
    island: "Palawan",
    location: "",
    dateFrom: "26.1.2023",
    dateTo: "",
    withBreakfast: false,
    priceCZK: "",
    priceCZKPerNight: "",
    typeOfSecondCurency: "",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "přelet Palawan - Bohol",
    url: "",
    slug: "",
    isTransfer: true,
  },
  {
    id: "015",
    country: "Filipíny",
    island: "Bohol",
    location: "Panglao",
    dateFrom: "26.1.2023",
    dateTo: "2.2.2023",
    withBreakfast: true,
    priceCZK: "6486",
    priceCZKPerNight: "926",
    typeOfSecondCurency: "PHP",
    priceSecondCurency: "16000",
    priceSecondCurencyPerNight: "2285",
    name: "CocoCabana",
    url: "https://goo.gl/maps/sgRxz9oGmz8bLfm76",
    slug: "panglao",
    isTransfer: false,
  },
  {
    id: "016",
    country: "Filipíny",
    island: "Bohol",
    location: "Panglao",
    dateFrom: "2.2.2023",
    dateTo: "16.2.2023",
    withBreakfast: false,
    priceCZK: "6100",
    priceCZKPerNight: "436",
    typeOfSecondCurency: "php",
    priceSecondCurency: "15400",
    priceSecondCurencyPerNight: "1100",
    name: "Moravian Apartments",
    url: "https://goo.gl/maps/31x5BdWcm8Jf4Q157",
    slug: "panglao",
    isTransfer: false,
  },
  {
    id: "017",
    country: "Filipíny",
    island: "Bohol",
    location: "",
    dateFrom: "16.2.2023",
    dateTo: "",
    withBreakfast: false,
    priceCZK: "",
    priceCZKPerNight: "",
    typeOfSecondCurency: "",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "přelet Bohol - Bali",
    url: "",
    slug: "",
    isTransfer: true,
  },
  {
    id: "018",
    country: "Indonésie",
    island: "Bali",
    location: "Sanur",
    dateFrom: "16.2.2023",
    dateTo: "21.2.2023",
    withBreakfast: true,
    priceCZK: "3100",
    priceCZKPerNight: "620",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "2200000",
    priceSecondCurencyPerNight: "440000",
    name: "Kamboja Homestay",
    url: "https://goo.gl/maps/YhT143PYsAw28aTFA",
    slug: "sanur",
    isTransfer: false,
  },
  {
    id: "019",
    country: "Indonésie",
    island: "Bali",
    location: "Sanur",
    dateFrom: "21.2.2023",
    dateTo: "23.2.2023",
    withBreakfast: false,
    priceCZK: "1530",
    priceCZKPerNight: "765",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "1070000",
    priceSecondCurencyPerNight: "535000",
    name: "Bestah Coliving",
    url: "https://goo.gl/maps/uSsjFt6QL22hzHnHA",
    slug: "sanur",
    isTransfer: false,
  },
  {
    id: "020",
    country: "Indonésie",
    island: "Bali",
    location: "Sanur",
    dateFrom: "23.2.2023",
    dateTo: "3.3.2023",
    withBreakfast: true,
    priceCZK: "4730",
    priceCZKPerNight: "591",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "3300000",
    priceSecondCurencyPerNight: "412000",
    name: "House of Michella",
    url: "https://goo.gl/maps/KEB2L4NpH1K959eP8",
    slug: "sanur",
    isTransfer: false,
  },
  {
    id: "021",
    country: "Indonésie",
    island: "Bali",
    location: "Sanur",
    dateFrom: "3.3.2023",
    dateTo: "3.4.2023",
    withBreakfast: false,
    priceCZK: "7200",
    priceCZKPerNight: "240",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "5000000",
    priceSecondCurencyPerNight: "167000",
    name: "Alya Living",
    url: "https://goo.gl/maps/sJYmzw7HK9hUuwT17",
    slug: "sanur",
    isTransfer: false,
  },
  {
    id: "022",
    country: "Indonésie",
    island: "Bali",
    location: "Amed",
    dateFrom: "19.3.2023",
    dateTo: "20.3.2023",
    withBreakfast: true,
    priceCZK: "290",
    priceCZKPerNight: "290",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "200000",
    priceSecondCurencyPerNight: "200000",
    name: "Cafe Divers Hotel",
    url: "https://goo.gl/maps/7Tfprf2cPeAQsGzp7",
    slug: "amed",
    isTransfer: false,
  },
  {
    id: "023",
    country: "Indonésie",
    island: "Bali",
    location: "Lovina",
    dateFrom: "30.3.2023",
    dateTo: "31.3.2023",
    withBreakfast: true,
    priceCZK: "460",
    priceCZKPerNight: "460",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "320000",
    priceSecondCurencyPerNight: "320000",
    name: "My Lovina",
    url: "",
    slug: "lovina",
    isTransfer: false,
  },
  {
    id: "0231",
    country: "Indonésie",
    island: "Bali",
    location: "Sanur",
    dateFrom: "3.4.2023",
    dateTo: "6.4.2023",
    withBreakfast: false,
    priceCZK: "1300",
    priceCZKPerNight: "433",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "900000",
    priceSecondCurencyPerNight: "300000",
    name: "Alya Living prodloužení",
    url: "https://goo.gl/maps/sJYmzw7HK9hUuwT17",
    slug: "sanur",
    isTransfer: false,
  },
  {
    id: "024",
    country: "Indonésie",
    island: "Bali",
    location: "",
    dateFrom: "6.4.2023",
    dateTo: "",
    withBreakfast: false,
    priceCZK: "4970",
    priceCZKPerNight: "",
    typeOfSecondCurency: "IDR",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "přelet Bali - Vietnam",
    url: "",
    slug: "",
    isTransfer: true,
  },
  {
    id: "025",
    country: "Vietnam",
    island: "",
    location: "Saigon",
    dateFrom: "6.4.2023",
    dateTo: "8.4.2023",
    withBreakfast: false,
    priceCZK: "814",
    priceCZKPerNight: "407",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "900000",
    priceSecondCurencyPerNight: "540000",
    name: "hostel saigon",
    url: "",
    slug: "saigon",
    isTransfer: false,
  },
  {
    id: "026",
    country: "Vietnam",
    island: "",
    location: "",
    dateFrom: "8.4.2023",
    dateTo: "",
    withBreakfast: false,
    priceCZK: "1945",
    priceCZKPerNight: "",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "přelet Saigon - Phukoc",
    url: "",
    slug: "",
    isTransfer: true,
  },
  {
    id: "027",
    country: "Vietnam",
    island: "",
    location: "Phu Quoc",
    dateFrom: "8.4.2023",
    dateTo: "13.4.2023",
    withBreakfast: true,
    priceCZK: "2313",
    priceCZKPerNight: "462",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "2556000",
    priceSecondCurencyPerNight: "512",
    name: "Bungalow Mai Phuong Binh",
    url: "",
    slug: "saigon",
    isTransfer: false,
  },
  {
    id: "028",
    country: "Vietnam",
    island: "",
    location: "Phu Quoc",
    dateFrom: "13.4.2023",
    dateTo: "",
    withBreakfast: false,
    priceCZK: "2380",
    priceCZKPerNight: "",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "přelet Phu quoc - Da-nang",
    url: "",
    slug: "",
    isTransfer: true,
  },
  {
    id: "029",
    country: "Vietnam",
    island: "",
    location: "Da-nang",
    dateFrom: "13.4.2023",
    dateTo: "20.4.2023",
    withBreakfast: true,
    priceCZK: "2739",
    priceCZKPerNight: "391",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "3 027 000",
    priceSecondCurencyPerNight: "432 000",
    name: "Fansipan Hotel",
    url: "",
    slug: "danang",
    isTransfer: false,
  },
  {
    id: "030",
    country: "Vietnam",
    island: "",
    location: "danang",
    dateFrom: "20.4.2023",
    dateTo: "",
    withBreakfast: false,
    priceCZK: "2130",
    priceCZKPerNight: "",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "přelet  Da-nang - Nha-trang",
    url: "",
    slug: "",
    isTransfer: true,
  },
  {
    id: "031",
    country: "Vietnam",
    island: "",
    location: "Nha-trang",
    dateFrom: "20.4.2023",
    dateTo: "27.4.2023",
    withBreakfast: true,
    priceCZK: "3067",
    priceCZKPerNight: "438",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "3 390 000",
    priceSecondCurencyPerNight: "484 000",
    name: "Sun City Hotel",
    url: "",
    slug: "nha-trang",
    isTransfer: false,
  },
  {
    id: "032",
    country: "Vietnam",
    island: "",
    location: "dalat",
    dateFrom: "27.4.2023",
    dateTo: "",
    withBreakfast: false,
    priceCZK: "724",
    priceCZKPerNight: "",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "prejezd Nha-trang - Dalat autem (cena jen za nas dva, auto stalo dvojnasobek)",
    url: "",
    slug: "",
    isTransfer: true,
  },
  {
    id: "033",
    country: "Vietnam",
    island: "",
    location: "Dalat",
    dateFrom: "27.4.2023",
    dateTo: "29.4.2023",
    withBreakfast: true,
    priceCZK: "1051",
    priceCZKPerNight: "525",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "1 162 000",
    priceSecondCurencyPerNight: "581 000",
    name: "SaiGon's Book Hotel",
    url: "",
    slug: "dalat",
    isTransfer: false,
  },
  {
    id: "034",
    country: "Vietnam",
    island: "",
    location: "canto",
    dateFrom: "29.4.2023",
    dateTo: "",
    withBreakfast: false,
    priceCZK: "1242",
    priceCZKPerNight: "",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "přelet Dalat - Canto ",
    url: "",
    slug: "",
    isTransfer: true,
  },
  {
    id: "035",
    country: "Vietnam",
    island: "",
    location: "Can Tho",
    dateFrom: "29.4.2023",
    dateTo: "30.4.2023",
    withBreakfast: true,
    priceCZK: "723",
    priceCZKPerNight: "723",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "800 000",
    priceSecondCurencyPerNight: "800 000",
    name: "KHÁCH SẠN KIM PHỤNG NGÂN",
    url: "",
    slug: "can-tho",
    isTransfer: false,
  },
  {
    id: "036",
    country: "Vietnam",
    island: "",
    location: "canto",
    dateFrom: "30.4.2023",
    dateTo: "",
    withBreakfast: false,
    priceCZK: "1075",
    priceCZKPerNight: "",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "prejezd canto - daigon autem (cena jen za nas dva, auto stalo dvojnasobek)",
    url: "",
    slug: "",
    isTransfer: true,
  },
  {
    id: "037",
    country: "Vietnam",
    island: "",
    location: "Saigon",
    dateFrom: "30.4.2023",
    dateTo: "4.5.2023",
    withBreakfast: true,
    priceCZK: "1786",
    priceCZKPerNight: "446",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "1 975 000",
    priceSecondCurencyPerNight: "494 000",
    name: "Grand Lee Hotel",
    url: "",
    slug: "saigon-2",
    isTransfer: false,
  },
  {
    id: "038",
    country: "Vietnam",
    island: "",
    location: "saigon",
    dateFrom: "4.5.2023",
    dateTo: "",
    withBreakfast: false,
    priceCZK: "28000",
    priceCZKPerNight: "",
    typeOfSecondCurency: "VND",
    priceSecondCurency: "",
    priceSecondCurencyPerNight: "",
    name: "přelet Vietnam - Praha ",
    url: "",
    slug: "",
    isTransfer: true,
  },
];
